project:
  type: website

website:
  title: "BioinfoHub @ CMM"
  site-url: https://bioinfohubcmm.github.io
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - href: past_events.qmd
        text: Past events
      - href: recommended_courses.qmd
        text: Recommended courses
      - href: about.qmd
        text: About
      - href: contacts.qmd
        text: Contact us

  page-footer:
    center: |
      © 2025 BioinfoHub @ CMM

format:
  html:
    theme: lumen
    css: styles.css

execute:
  freeze: auto



