site_name: BioinfoHubCMM
nav:
  - Home: index.md
  - Events:
    - Upcoming events: events.md
    - Past events: past_events.md
  - About: about.md
  - Contact us: contacts.md

theme: 
  name: flatly
  logo: ./BioinfoHubCMM.github.io/assets/images/BioInfoHubLogo_1.png
  favicon: ./BioinfoHubCMM.github.io/assets/images/BioInfoHubLogo_1.png
#  custom_dir: overrides

site_author: Ana Cristina Gonzalez-Sanchez

# Extras
extra_css: 
  - css/extra.css
extra_javascript:
  - jss/extra.jss

# Site
site_url: https://bioinfohubcmm.github.io/
use_directory_urls: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Anacristina0914/
      name: Ana Cristina Gonzalez-Sanchez
